# -*- coding: utf-8 -*-
"""Analysis&visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lj_bh1GW-zv73qGKxsblFGN--te6Bgy4
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap
import warnings
warnings.filterwarnings("ignore")

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.color": "#EBEBEB",
    "grid.linewidth": 0.7,
    "axes.labelcolor": "#333333",
    "xtick.color": "#555555",
    "ytick.color": "#555555",
    "figure.facecolor": "white",
    "axes.facecolor": "white",
})

BLUE   = "#1F5C8B"
DBLUE  = "#0D3C6E"
LBLUE  = "#5BA4CF"
RED    = "#D94F3D"
ORANGE = "#E87D2B"
GREEN  = "#3CA668"
PURPLE = "#8B5CF6"
GREY   = "#9CA3AF"
TEAL   = "#0891B2"
GOLD   = "#D97706"

TOD_COLORS = {
    "Morning Rush": "#F59E0B",
    "Mid Morning":  "#10B981",
    "Afternoon":    "#3B82F6",
    "Evening Rush": "#EF4444",
    "Night":        "#6366F1",
    "Late Night":   "#8B5CF6",
}

SEASON_COLORS = {"Fall": "#E87D2B", "Winter": "#5BA4CF", "Spring": "#3CA668", "Summer": "#D94F3D"}
DAY_ORDER = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

# Load  dataset
df = pd.read_csv("/content/sample_data/traffic_collision_cleaned.csv")

# Objective 1 ── Peak Hours
ph = (df.groupby(["Hour","Time_of_Day"])
        .agg(Total_Collisions=("DR_Number","count"))
        .reset_index()
        .sort_values("Hour"))

rush = df[((df["Hour"]>=7)&(df["Hour"]<=9))|((df["Hour"]>=17)&(df["Hour"]<=19))]
rush_s = (rush.groupby(["Time_of_Day","Hour"])
              .agg(Rush_Collisions=("DR_Number","count"))
              .reset_index()
              .sort_values(["Time_of_Day","Hour"]))

day_p = (df.groupby("Day_of_Week")
           .agg(Total_Collisions=("DR_Number","count"), Avg_Victim_Age=("Victim_Age","mean"))
           .reset_index()
           .sort_values("Total_Collisions", ascending=False))

wvw = (df.groupby("Is_Weekend")
         .agg(Total_Collisions=("DR_Number","count"), Distinct_Days=("Date_Occurred","nunique"))
         .reset_index())
wvw["Avg_Daily"] = (wvw["Total_Collisions"]/wvw["Distinct_Days"]).round(1)

seasonal = (df.groupby("Season")
              .agg(Total_Collisions=("DR_Number","count"))
              .reset_index()
              .sort_values("Total_Collisions", ascending=False))

# Objective 2 ── Congested Routes
da = (df.groupby("Area_Name")
        .agg(Total_Collisions=("DR_Number","count"),
             Hotspot_Count=("Is_Hotspot","sum"),
             Avg_Victim_Age=("Victim_Age","mean"))
        .reset_index()
        .sort_values("Total_Collisions", ascending=False))

sev = (df.groupby(["Area_Name","Collision_Severity"])
         .agg(Count=("DR_Number","count"))
         .reset_index())
sev_pivot = sev.pivot(index="Area_Name", columns="Collision_Severity", values="Count").fillna(0).reset_index()
sev_pivot = sev_pivot.merge(da[["Area_Name","Total_Collisions"]], on="Area_Name").sort_values("Total_Collisions", ascending=False)

# Peak per area (Aggregation + Window + Join)
hba = df.groupby(["Area_Name","Hour"]).agg(Hourly_Count=("DR_Number","count")).reset_index()
peak_per = hba.loc[hba.groupby("Area_Name")["Hourly_Count"].idxmax()].rename(
    columns={"Hour":"Peak_Hour","Hourly_Count":"Peak_Collisions"})
peak_area = da.merge(peak_per, on="Area_Name", how="left").sort_values("Total_Collisions", ascending=False)

# Objective 3 ── Flow Patterns
yt = (df.groupby("Year")
        .agg(Total_Collisions=("DR_Number","count"))
        .reset_index()
        .sort_values("Year"))

mt = (df.groupby(["Month","Season"])
        .agg(Total_Collisions=("DR_Number","count"))
        .reset_index()
        .sort_values("Month"))
MONTH_NAMES = {1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",
               7:"Jul",8:"Aug",9:"Sep",10:"Oct",11:"Nov",12:"Dec"}
mt["MonthName"] = mt["Month"].map(MONTH_NAMES)

hf77 = (df[df["Area_Name"]=="77th Street"]
          .groupby(["Hour","Time_of_Day"])
          .agg(Collision_Count=("DR_Number","count"))
          .reset_index()
          .sort_values("Hour"))

covid = (df[df["Year"].isin([2018,2019,2020,2021,2022])]
           .groupby(["Year","Month"])
           .agg(Monthly_Collisions=("DR_Number","count"))
           .reset_index()
           .sort_values(["Year","Month"]))
covid["MonthName"] = covid["Month"].map(MONTH_NAMES)

# RDD MapReduce result
rdd = (df.groupby(["Area_Name","Hour"])
         .agg(Collision_Count=("DR_Number","count"))
         .reset_index()
         .sort_values("Collision_Count", ascending=False))

# Hours across 24h for full heatmap
heatmap_data = (df.groupby(["Area_Name","Hour"])
                  .agg(Count=("DR_Number","count"))
                  .reset_index()
                  .pivot(index="Area_Name", columns="Hour", values="Count")
                  .fillna(0))
heatmap_data = heatmap_data.loc[da["Area_Name"].tolist()]  # sorted by total

# FIGURE 1 — OBJECTIVE 1: PEAK TRAFFIC HOURS  (2 × 3)

fig1 = plt.figure(figsize=(20, 13))
fig1.suptitle("OBJECTIVE 1 — Peak Traffic Hours Analysis", fontsize=18, fontweight="bold",
              color=DBLUE, y=0.98)

gs = gridspec.GridSpec(2, 3, figure=fig1, hspace=0.42, wspace=0.38)

# Plot 1a: Hourly collision count bar (coloured by time-of-day)
ax1 = fig1.add_subplot(gs[0, :2])
colors = [TOD_COLORS.get(t, BLUE) for t in ph["Time_of_Day"]]
bars = ax1.bar(ph["Hour"], ph["Total_Collisions"], color=colors, edgecolor="white", linewidth=0.5, width=0.75)
ax1.set_xlabel("Hour of Day", fontsize=11)
ax1.set_ylabel("Total Collisions", fontsize=11)
ax1.set_title("Collisions by Hour of Day  (coloured by Time-of-Day)", fontsize=12, fontweight="bold")
ax1.set_xticks(range(0, 24))
ax1.set_xticklabels([f"{h:02d}" for h in range(24)], fontsize=8)
# Annotate peak
peak_row = ph.sort_values("Total_Collisions", ascending=False).iloc[0]
ax1.annotate(f'Peak\n{int(peak_row.Total_Collisions):,}',
             xy=(peak_row.Hour, peak_row.Total_Collisions),
             xytext=(peak_row.Hour+1.5, peak_row.Total_Collisions+80),
             fontsize=9, color=RED, fontweight="bold",
             arrowprops=dict(arrowstyle="->", color=RED, lw=1.4))
legend_patches = [mpatches.Patch(color=c, label=t) for t, c in TOD_COLORS.items()]
ax1.legend(handles=legend_patches, fontsize=8, loc="upper left", ncol=3, framealpha=0.8)

# ── Plot 1b: Rush hour breakdown
ax2 = fig1.add_subplot(gs[0, 2])
rush_colors = [TOD_COLORS.get(t, BLUE) for t in rush_s["Time_of_Day"]]
ax2.barh(rush_s.apply(lambda r: f"{int(r.Hour):02d}:00\n({r.Time_of_Day.split()[0]})", axis=1),
         rush_s["Rush_Collisions"], color=rush_colors, edgecolor="white")
ax2.set_xlabel("Rush Collisions", fontsize=10)
ax2.set_title("Rush Hour Breakdown)", fontsize=12, fontweight="bold")
for i, v in enumerate(rush_s["Rush_Collisions"]):
    ax2.text(v+30, i, f"{v:,}", va="center", fontsize=8, color="#333333")

# ── Plot 1c: Day of week ──────────────────────────────────────────────────────
ax3 = fig1.add_subplot(gs[1, 0])
day_ordered = day_p.set_index("Day_of_Week").reindex(DAY_ORDER).reset_index()
bar_colors = [ORANGE if d in ["Friday","Saturday"] else BLUE for d in day_ordered["Day_of_Week"]]
ax3.bar(day_ordered["Day_of_Week"], day_ordered["Total_Collisions"],
        color=bar_colors, edgecolor="white")
ax3.set_xlabel("")
ax3.set_ylabel("Collisions", fontsize=10)
ax3.set_title("Collisions by Day of Week", fontsize=12, fontweight="bold")
ax3.set_xticklabels(day_ordered["Day_of_Week"], rotation=35, ha="right", fontsize=9)
ax3.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{int(x):,}"))

# ── Plot 1d: Weekend vs Weekday ───────────────────────────────────────────────
ax4 = fig1.add_subplot(gs[1, 1])
labels = ["Weekday", "Weekend"]
totals = [wvw[wvw["Is_Weekend"]==False]["Total_Collisions"].values[0],
          wvw[wvw["Is_Weekend"]==True]["Total_Collisions"].values[0]]
avgs   = [wvw[wvw["Is_Weekend"]==False]["Avg_Daily"].values[0],
          wvw[wvw["Is_Weekend"]==True]["Avg_Daily"].values[0]]
x = np.arange(2)
w = 0.38
b1 = ax4.bar(x - w/2, totals, width=w, color=[BLUE, ORANGE], label="Total", edgecolor="white")
ax4b = ax4.twinx()
ax4b.bar(x + w/2, avgs, width=w, color=[LBLUE, GOLD], alpha=0.8, label="Avg Daily", edgecolor="white")
ax4b.set_ylabel("Avg Daily Collisions", fontsize=9, color=GOLD)
ax4b.tick_params(axis='y', colors=GOLD)
ax4b.spines["right"].set_visible(True)
ax4b.spines["right"].set_color("#DDDDDD")
ax4.set_xticks(x)
ax4.set_xticklabels(labels, fontsize=10)
ax4.set_ylabel("Total Collisions", fontsize=10)
ax4.set_title("Weekend vs Weekday", fontsize=12, fontweight="bold")
for bar, v in zip(b1, totals):
    ax4.text(bar.get_x()+bar.get_width()/2, v+100, f"{v:,}", ha="center", fontsize=9)

import os

# ── Plot 1e: Seasonal ─────────────────────────────────────────────────────────
ax5 = fig1.add_subplot(gs[1, 2])
season_order = ["Spring","Summer","Fall","Winter"]
seas = seasonal.set_index("Season").reindex(season_order).reset_index()
wedge_colors = [SEASON_COLORS[s] for s in seas["Season"]]
wedges, texts, autotexts = ax5.pie(
    seas["Total_Collisions"], labels=seas["Season"],
    colors=wedge_colors, autopct="%1.1f%%", startangle=90,
    pctdistance=0.75, textprops={"fontsize": 10},
    wedgeprops={"edgecolor":"white","linewidth":1.5})
for at in autotexts: at.set_fontsize(9); at.set_color("white"); at.set_fontweight("bold")
ax5.set_title("Collision Distribution\nby Season", fontsize=12, fontweight="bold")

os.makedirs('outputs', exist_ok=True)
fig1.savefig("outputs/fig1_peak_hours.png", dpi=150, bbox_inches="tight")
plt.close(fig1)
print("✅ Fig 1 saved: fig1_peak_hours.png")

# FIGURE 2 — OBJECTIVE 2: CONGESTED ROUTES  (2 × 2)

fig2 = plt.figure(figsize=(20, 14))
fig2.suptitle("OBJECTIVE 2 — Congested Routes & High-Risk Districts", fontsize=18,
              fontweight="bold", color=DBLUE, y=0.98)
gs2 = gridspec.GridSpec(2, 2, figure=fig2, hspace=0.42, wspace=0.35)

#Plot 2a: Top-10 dangerous districts (horizontal bar)
ax6 = fig2.add_subplot(gs2[0, :])
top10 = da.head(10).sort_values("Total_Collisions")
bar_colors = plt.cm.Reds(np.linspace(0.35, 0.85, len(top10)))
bars = ax6.barh(top10["Area_Name"], top10["Total_Collisions"],
                color=bar_colors, edgecolor="white")
ax6.set_xlabel("Total Collisions", fontsize=11)
ax6.set_title("Top 10 Most Dangerous Districts)", fontsize=13, fontweight="bold")
ax6.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{int(x):,}"))
# Hotspot overlay
ax6b = ax6.twiny()
ax6b.barh(top10["Area_Name"], top10["Hotspot_Count"],
          color="none", edgecolor=RED, linewidth=2, linestyle="--", height=0.6,
          label="Hotspot Count")
ax6b.set_xlabel("Hotspot Count", fontsize=10, color=RED)
ax6b.tick_params(axis='x', colors=RED)
ax6b.spines["top"].set_color(RED)
for bar, v, hc in zip(bars, top10["Total_Collisions"], top10["Hotspot_Count"]):
    ax6.text(v+30, bar.get_y()+bar.get_height()/2,
             f"{v:,}  (HS: {hc:,})", va="center", fontsize=9)
ax6b.legend(loc="lower right", fontsize=9)

# Plot 2b: Severity stacked bar
ax7 = fig2.add_subplot(gs2[1, 0])
sev10 = sev_pivot.head(10).sort_values("Total_Collisions")
inj_col = "Injury Involved"
prop_col = "Property Damage Only"
ax7.barh(sev10["Area_Name"], sev10.get(inj_col, 0), color=RED, label="Injury Involved", edgecolor="white")
ax7.barh(sev10["Area_Name"], sev10.get(prop_col, 0),
         left=sev10.get(inj_col, 0), color=ORANGE, label="Property Damage Only", edgecolor="white")
ax7.set_xlabel("Collision Count", fontsize=10)
ax7.set_title("Severity Breakdown\nby District)", fontsize=12, fontweight="bold")
ax7.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{int(x):,}"))
ax7.legend(fontsize=9, loc="lower right")

#Plot 2c: Peak hour per district scatter
ax8 = fig2.add_subplot(gs2[1, 1])
sc = ax8.scatter(peak_area["Peak_Hour"], peak_area["Total_Collisions"],
                 c=peak_area["Hotspot_Count"], cmap="YlOrRd",
                 s=120, edgecolors="white", linewidths=0.8, alpha=0.9)
cb = fig2.colorbar(sc, ax=ax8, pad=0.02)
cb.set_label("Hotspot Count", fontsize=9)
ax8.set_xlabel("Peak Collision Hour", fontsize=11)
ax8.set_ylabel("Total Collisions", fontsize=11)
ax8.set_title("Peak Hour per District)", fontsize=12, fontweight="bold")
ax8.set_xticks(range(0,24,2))
ax8.set_xticklabels([f"{h:02d}" for h in range(0,24,2)], fontsize=8)
ax8.yaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f"{int(x):,}"))
# Annotate top 5
for _, row in peak_area.head(5).iterrows():
    ax8.annotate(row["Area_Name"], xy=(row["Peak_Hour"], row["Total_Collisions"]),
                 xytext=(row["Peak_Hour"]+0.3, row["Total_Collisions"]+50),
                 fontsize=7.5, color=DBLUE)

fig2.savefig("outputs/fig2_congested_routes.png", dpi=150, bbox_inches="tight")
plt.close(fig2)
print("✅ Fig 2 saved: fig2_congested_routes.png")

# FIGURE 3 — HEATMAP: Area × Hour collision density (RDD MapReduce)

fig3, ax9 = plt.subplots(figsize=(22, 9))
fig3.suptitle("Area × Hour Collision Heatmap  (Section [16] — RDD MapReduce Pattern)",
              fontsize=16, fontweight="bold", color=DBLUE, y=1.01)

cmap = LinearSegmentedColormap.from_list("traffic", ["#EFF6FF","#BFDBFE","#3B82F6","#1E3A8A","#7C0000"])
im = ax9.imshow(heatmap_data.values, aspect="auto", cmap=cmap, interpolation="nearest")
ax9.set_xticks(range(24))
ax9.set_xticklabels([f"{h:02d}:00" for h in range(24)], fontsize=8, rotation=45, ha="right")
ax9.set_yticks(range(len(heatmap_data.index)))
ax9.set_yticklabels(heatmap_data.index, fontsize=8.5)
ax9.set_xlabel("Hour of Day", fontsize=11)
ax9.set_ylabel("District (Area Name)", fontsize=11)
cb = fig3.colorbar(im, ax=ax9, pad=0.01, fraction=0.02)
cb.set_label("Collision Count", fontsize=10)
# Vertical lines for rush hours
for h in [7, 9, 17, 19]:
    ax9.axvline(h - 0.5, color="white", linewidth=1.2, linestyle="--", alpha=0.7)

fig3.savefig("outputs/fig3_heatmap_area_hour.png", dpi=150, bbox_inches="tight")
plt.close(fig3)
print("✅ Fig 3 saved: fig3_heatmap_area_hour.png")

# FIGURE 4 — OBJECTIVE 3: VEHICLE FLOW PATTERNS  (2 × 3)

fig4 = plt.figure(figsize=(20, 13))
fig4.suptitle("OBJECTIVE 3 — Vehicle Flow Patterns Analysis", fontsize=18,
              fontweight="bold", color=DBLUE, y=0.98)
gs4 = gridspec.GridSpec(2, 3, figure=fig4, hspace=0.45, wspace=0.38)

# Plot 4b: Monthly collision frequency
ax11 = fig4.add_subplot(gs4[0, 2])
bar_colors_m = [SEASON_COLORS[s] for s in mt["Season"]]
ax11.bar(mt["MonthName"], mt["Total_Collisions"], color=bar_colors_m, edgecolor="white")
ax11.set_xlabel("Month", fontsize=10)
ax11.set_ylabel("Collisions", fontsize=10)
ax11.set_title("Monthly Flow Pattern)", fontsize=12, fontweight="bold")
ax11.yaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f"{int(x):,}"))
ax11.tick_params(axis="x", labelsize=8, rotation=30)
season_patches = [mpatches.Patch(color=c, label=s) for s,c in SEASON_COLORS.items()]
ax11.legend(handles=season_patches, fontsize=8, loc="upper left")

# Plot 4c: 77th Street hourly flow (Section [15])
ax12 = fig4.add_subplot(gs4[1, :2])
h77colors = [TOD_COLORS.get(t, BLUE) for t in hf77["Time_of_Day"]]
bars77 = ax12.bar(hf77["Hour"], hf77["Collision_Count"], color=h77colors, edgecolor="white", width=0.75)
ax12.set_xlabel("Hour of Day", fontsize=11)
ax12.set_ylabel("Collision Count", fontsize=11)
ax12.set_title("Hourly Traffic Flow — 77th Street District)", fontsize=12, fontweight="bold")
ax12.set_xticks(range(0,24))
ax12.set_xticklabels([f"{h:02d}" for h in range(24)], fontsize=8)
ax12.legend(handles=legend_patches, fontsize=8, ncol=3, loc="upper left")

fig4.savefig("outputs/fig4_flow_patterns.png", dpi=150, bbox_inches="tight")
plt.close(fig4)
print("✅ Fig 4 saved: fig4_flow_patterns.png")

# FIGURE 5 — RDD MapReduce: Top Area-Hour Pairs + Full Hourly Distribution

fig5 = plt.figure(figsize=(20, 10))
fig5.suptitle("RDD MapReduce Pattern — (Area, Hour) Key-Value Collision Counts  (Section [16])",
              fontsize=16, fontweight="bold", color=DBLUE, y=0.99)
gs5 = gridspec.GridSpec(1, 2, figure=fig5, wspace=0.38)

# Plot 5a: Top 20 Area-Hour pairs
ax14 = fig5.add_subplot(gs5[0, 0])
top20rdd = rdd.head(20).sort_values("Collision_Count")
labels_rdd = top20rdd.apply(lambda r: f"{r.Area_Name}  [{int(r.Hour):02d}:00]", axis=1)
bar_colors_rdd = plt.cm.YlOrRd(np.linspace(0.3, 0.9, len(top20rdd)))
ax14.barh(labels_rdd, top20rdd["Collision_Count"], color=bar_colors_rdd, edgecolor="white")
ax14.set_xlabel("Collision Count", fontsize=11)
ax14.set_title("Top 20 (Area, Hour) Pairs\nby Collision Count", fontsize=12, fontweight="bold")
for i, v in enumerate(top20rdd["Collision_Count"]):
    ax14.text(v+2, i, str(v), va="center", fontsize=8.5)

#Plot 5b: Full 24h distribution across all areas (violin-style using lines)
ax15 = fig5.add_subplot(gs5[0, 1])
area_hour_pivot = rdd.pivot_table(index="Hour", columns="Area_Name", values="Collision_Count", fill_value=0)
hourly_total = area_hour_pivot.sum(axis=1).reset_index()
hourly_total.columns = ["Hour","Total"]
hourly_mean  = area_hour_pivot.mean(axis=1).reset_index()
hourly_mean.columns  = ["Hour","Mean"]
hourly_max   = area_hour_pivot.max(axis=1).reset_index()
hourly_max.columns   = ["Hour","Max"]
hourly_min   = area_hour_pivot.min(axis=1).reset_index()
hourly_min.columns   = ["Hour","Min"]

ax15.fill_between(hourly_min["Hour"], hourly_min["Min"], hourly_max["Max"],
                  alpha=0.2, color=BLUE, label="Min–Max range")
ax15.plot(hourly_mean["Hour"], hourly_mean["Mean"], color=BLUE, linewidth=2.5, label="Mean per area")
ax15.plot(hourly_total["Hour"], hourly_total["Total"] / hourly_total["Total"].max() * hourly_mean["Mean"].max(),
          color=RED, linewidth=2, linestyle="--", label="Total (normalised)")
ax15.set_xlabel("Hour of Day", fontsize=11)
ax15.set_ylabel("Collision Count (per area)", fontsize=11)
ax15.set_title("Hourly Collision Distribution\nAcross All Districts", fontsize=12, fontweight="bold")
ax15.set_xticks(range(0,24,2))
ax15.set_xticklabels([f"{h:02d}:00" for h in range(0,24,2)], rotation=30, fontsize=8)
ax15.legend(fontsize=9)

fig5.savefig("outputs/fig5_rdd_mapreduce.png", dpi=150, bbox_inches="tight")
plt.close(fig5)
print("✅ Fig 5 saved: fig5_rdd_mapreduce.png")

